name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    # needs: laravel-tests  # Only proceed if Laravel tests succeed
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          environment: production
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USER }}
          # key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SVR_DIR }}
            git pull origin main
            cd html
            npm run build
